appName: webapi-dev
replicas: 1

configmap:
  name: webapi-dev-configmap-v7
  data:
    environment: Development
    default_loglevel: Debug
    aspnet_loglevel: Information
    api_token: supersecret
image:
  name: tomasr/webapi
  tag: 8
