appName: my-helm-webapi
replicas: 3

configmap:
  name: myhelmapp-configmap-v2
  data:
    environment: "Production"

image:
  name: tomasr/webapi
  tag: 1
  
service:
  type: ClusterIP
  port: 8080
  
ingress:
  enabled: false