appName: my-helm-webapi
replicas: 3

configmap:
  name: myhelmapp-configmap-v2
  data:
    environment: Production
    default_loglevel: Information
    aspnet_loglevel: Warning
    api_token:

image:
  name: tomasr/webapi
  tag: 3
  
service:
  type: ClusterIP
  port: 9300
  
ingress:
  enabled: false