appName: my-helm-webapi
replicas: 3

configmap:
  name: myhelmapp-configmap-v2
  data:
    environment: Production
    default_loglevel: Information

image:
  name: tomasr/webapi
  tag: 1
  
service:
  type: ClusterIP
  port: 9300
  
ingress:
  enabled: false