kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ .Values.configmap.name }}
data:
  ASPNETCORE__ENVIRONMENT: {{.Values.configmap.data.environment | quote}}
  Logging__LogLevel__Default: {{.Values.configmap.data.default_loglevel | quote}}

