kind: ConfigMap
apiVersion: v1
metadata:
  name: {{include "helm-webapp.fullname" .}}-config
  labels:
    {{- include "helm-webapp.labels" . | nindent 4 }}
data:
  ASPNETCORE_ENVIRONMENT: {{.Values.configmap.data.environment | quote}}
  Logging__LogLevel__Default: {{.Values.configmap.data.default_loglevel | quote}}
  Logging__LogLevel__Microsoft.AspNetCore: {{.Values.configmap.data.aspnet_loglevel| quote}}
  ApiToken: {{.Values.configmap.data.api_token | quote}}