apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appName }}
  labels:
    app: {{ .Values.appName }}
    checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum | trunc 32 }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      {{- include "helm-webapp.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "helm-webapp.selectorLabels" . | nindent 8 }}
    spec: # Pod spec
      containers:
        - name: webapi
          image: "{{ .Values.image.name }}:{{ .Values.image.tag }}"
          ports:
            - name: http
              containerPort: 9300
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 10
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /health
              port: http
          envFrom:
            - configMapRef:
                name: {{ .Values.configmap.name }}

          resources:
            requests:
              memory: "128Mi"
              cpu: "150m"    # 500milliCPUs (1/2 CPU)
           