apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{include "helm-webapp.fullname" .}}
  labels:
    {{- include "helm-webapp.labels" . | nindent 4 }}
    checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum | trunc 32 }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      {{- include "helm-webapp.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "helm-webapp.selectorLabels" . | nindent 8 }}
      annotations:
        vault.hashicorp.com/tls_skip_verify: 'true'
        vault.hashicorp.com/agent-inject: 'true'
        vault.hashicorp.com/role: 'weatherapi'
        vault.hashicorp.com/agent-inject-secret-api.env: '/kv/weatherapi'
        vault.hashicorp.com/agent-inject-template-api.env: |
         {{`{{- with secret "/kv/weatherapi" -}}
              export ApiToken="{{- .Data.data.ApiToken -}}"
            {{- end -}}`}}
        vault.hashicorp.com/ca-cert: "/run/secrets/kubernetes.io/serviceaccount/ca.crt"
    spec: # Pod spec
      serviceAccountName: weatherapi
      containers:
        - name: webapi
          image: "{{ .Values.image.name }}:{{ .Values.image.tag }}"
          ports:
            - name: http
              containerPort: 9300
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 10
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /health
              port: http
          command: ['/bin/bash', '-c']
          args: ["source /vault/secrets/api.env", "dotnet /app/WebApi.dll"]
          envFrom:
            - configMapRef:
                name: {{include "helm-webapp.fullname" .}}-config
        
          resources:
            requests:
              memory: "128Mi"
              cpu: "150m"    # 500milliCPUs (1/2 CPU)
           
      